### ISSUE TITLE
Disable options to add new files or directories to repositories

### ISSUE THREAD

**Issue by dbarranco** [patrikx3/gitlist#29]
Hello!

Thanks much for your work here, my team has been using Gitlist for a while and we are now considering on moving to this fork :).

I'd like to ask if it could be possible to disable the `Add New file or directory` and `Upload file and/or override binary`, as our main use case for Gitlist is to use it as a read-only interface for our internal Git repository.

At the end, what I would like is to avoid this kind of situations:
https://gitlist.patrikx3.com/redis-ui.git/blob/master/hey

(sorry for the file, I created it 😓 )

Thanks again!

**Comment by Zaptopod4001** [comment]
So what does that mean? You closed my issues, but "disable read only viewer" has nothing to with that question - I asked - "can I disable editing of files" - which is quite the opposite. Or is this just some bot talking nonsense....
